import type { Metadata } from "next";
import { Fredoka, Mountains_of_Christmas, Nunito } from "next/font/google";
import { auth } from "@/auth";
import { prisma } from "@/lib/db";
import { AppShell } from "@/components/shell/app-shell";
import "./globals.css";

const fredoka = Fredoka({
  variable: "--font-fredoka",
  subsets: ["latin"],
});

// Hand-lettered festive face for the big page titles only; Fredoka carries
// the smaller headings where legibility matters more.
const mountains = Mountains_of_Christmas({
  variable: "--font-mountains",
  weight: ["400", "700"],
  subsets: ["latin"],
});

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  metadataBase: new URL("https://jinglejotter.markrwatts.com"),
  title: "Jingle Jotter",
  description: "Keep the Christmas budget merry and bright",
  icons: { icon: "/brand/icon.png" },
  // Link previews (WhatsApp, iMessage, Slack…). Generated by the sender's
  // device, so they work for anyone on the LAN pasting the link.
  openGraph: {
    title: "Jingle Jotter",
    description: "Keep the Christmas budget merry and bright",
    siteName: "Jingle Jotter",
    type: "website",
    locale: "en_GB",
    images: [{ url: "/brand/login-desktop.png", width: 1774, height: 887 }],
  },
  twitter: {
    card: "summary_large_image",
    title: "Jingle Jotter",
    description: "Keep the Christmas budget merry and bright",
    images: ["/brand/login-desktop.png"],
  },
};

export default async function RootLayout({ children }: LayoutProps<"/">) {
  // Festive-decoration switch: stamped on <body> so pure decorations
  // (.whimsy-decor) can hide with one CSS rule, per signed-in user.
  const session = await auth();
  let showWhimsy = true;
  if (session?.user?.id) {
    const user = await prisma.user.findUnique({
      where: { id: session.user.id },
      select: { showWhimsy: true },
    });
    showWhimsy = user?.showWhimsy ?? true;
  }

  return (
    <html
      lang="en"
      className={`${fredoka.variable} ${mountains.variable} ${nunito.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col" data-whimsy={showWhimsy ? "on" : "off"}>
        <AppShell>{children}</AppShell>
      </body>
    </html>
  );
}
